### PR TITLE
[Linux] Dynamically find device sink name

### LINKED ISSUE #107: [Linux] 'a2dp-sink' is called 'a2dp_sink' on Arch Linux
Hello, I recently discovered this project and really like it! I've built the new Linux app but I've been getting the following error when activating the A2DP profile:
```
Failure: No such entity
airpodsApp:  Failed to activate A2DP profile 
```

I noticed that this was because [the pactl command](https://github.com/kavishdevar/aln/blob/ed0de4d9fac7fd125f03b8acba26095af9baebb2/linux/mediacontroller.cpp#L196) to activate this profile uses `a2dp-sink`, whereas on Arch Linux, it is `a2dp_sink`. I'm not sure where exactly this discrepancy comes from.

I think a potential solution could be to try `a2dp-sink`, and then fallback to `a2dp_sink` if the first command fails. I can definitely submit a PR with whatever decision is decided as well.

### PR DESCRIPTION
**Pull request by tim-gromeyer**
Should fix #107, needs testing (works for me)

Should work on pipewire and pulseaudio systems.

### CODE REVIEW

File: linux/mediacontroller.cpp [hunk 1]
```diff
@@ -252,4 +254,51 @@ MediaController::~MediaController() {
...
+  // Use a cleaner MAC address format for PulseAudio matching
+  QProcess process;
+  process.start("pactl", QStringList() << "list" << "sinks");
+  process.waitForFinished();
+
+  QString output = process.readAllStandardOutput();
+  if (output.isEmpty())
+  {
+    QProcess process;
+    process.start("pactl", QStringList() << "list" << "sinks");
```
Comment (kavishdevar) [inline linux/mediacontroller.cpp]: `pactl list short sinks` might be better, and then `awk '$2 ~ /^bluez/ {print $2}'`

**Comment by tim-gromeyer** [comment]
@jdholtz @kavishdevar, please test and give feedback. Will take care of https://github.com/kavishdevar/aln/issues/107#issuecomment-2826575041 later


Edit: Couldn't reproduce, it works for me after last commit https://github.com/kavishdevar/aln/pull/108/commits/bc655570c7b90721953748eb1587e382350e7f6c

**Comment by kavishdevar** [comment]
works for me!

**Comment by tim-gromeyer** [comment]
Since the other guy is not responding, let's just merge. Can be adjusted later om if it doesn't work
